# Default values for wordpress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 2

metadata:
  wordpress:
    name: wordpress
  sql:
    name: wordpress-mysql

nodeLabels:
  hostname: raspberrypi4

labels:
  app: wordpress

ports:
  containerPort: 443
  sqlport: 3306

containers:
  wordpress:
    image: wordpress
    name: wordpress
  mysql:
      image: mysql:8.0
      name: mysql

wp_deployment_volumes: 
  volumes:
    name: wordpress-persistent-storage
    persistentVolumeClaim:
      claimName: wp-pv-claim
  volumeMounts:
    name: wordpress-persistent-storage
    mountPath: /var/www/html


mysql_deployment_volumes:
  volumeMounts:
  - name: mysql-persistent-storage
    mountPath: /var/lib/mysql
  volumes:
  - name: mysql-persistent-storage
    persistentVolumeClaim:
     claimName: mysql-pv-claim

services:
  wp_deployment:
    type: LoadBalancer
  mysql:
    selector:

accessModes: ReadWriteOnce

env:
  mysql:
  - name: MYSQL_ROOT_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mysql-pass-8cdkhkh8hd
        key: password
  - name: MYSQL_DATABASE
    value: wordpress
  - name: MYSQL_USER
    value: wordpress
  - name: MYSQL_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mysql-pass
        key: password
  wordpress:
    - name: WORDPRESS_DB_HOST
      value: wordpress-mysql
    - name: WORDPRESS_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-pass-8cdkhkh8hd
          key: password
    - name: WORDPRESS_DB_USER
      value: wordpress

requests:
  storage: 20Gi