apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.containers.name }}
  labels:
    app: {{ .Values.labels.app }}
spec:
  ports:
    - port: {{ .Values.ports.containerPort }}
  selector:
    app: {{ .Values.labels.app }}
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: {{ .Values.labels.app }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.labels.app }}
  name: {{ .Values.containers.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      kubernetes.io/hostname: {{ .Values.nodeLabels.kubernetes.io/hostname }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.labels.app }}
    spec:
      containers:
      - image: {{ .Values.containers.image }}
        name: {{ .Values.containers.name }}
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: WORDPRESS_DB_USER
          value: wordpress
        resources: {}
        ports:
            - port: {{ .Values.ports.containerPort }}
        volumeMounts:
        - name: {{ .Values.wp_deployment.volumes.name }}
          mountPath: /var/www/html
      volumes:
      - name: {{ .Values.wp_deployment.volumeMounts.name }}
        persistentVolumeClaim:
          claimName: wp-pv-claim

status: {}